### ISSUE TITLE
Sequelize v4 support

### ISSUE THREAD

**Issue by sameoldmadness** [allmas-tn/sequelize-transforms#4]
Seems like since v4 `target instanceof Sequelize.Model` no longer a valid way to check if value is a Model.

I want to provide a PR, but it'll take some time for me to get familiar with Sequelize's internals.

Do you have any observations/suggestion on this issue?

**Comment by sameoldmadness** [comment]
So far I see two issues:

* model becomes a class, so the check should be smth like `target.prototype instanceof Sequelize.Model`
* if app uses different version of Sequelize, `instanceof Sequelize.Model` will not work at all.

As a quick suggestion, duck typing may help:

```js
target instanceof Sequelize.Model || target.init
```

**Comment by sameoldmadness** [comment]
~~For whatever reason transforms are not called on attributes with `TEXT` type, so I'll opt out to hooks for now.~~

Sorry for the mess : )

**Comment by hbj** [comment]
I didn't work with Sequelize v4, so I don't know more than you do about it :) A PR is welcome if you make it and I'll try to find time for this. I'll reopen the issue so we can track suggestions.

**Comment by sameoldmadness** [comment]
~~For the record: [this piece of code](https://github.com/allmas-tn/sequelize-transforms/blob/master/index.js#L48-L51) may be broken for some attribute types (i.e. TEXT) in v4.~~

**Comment by andrew-makarenko** [comment]
this fix is really needed

**Comment by sameoldmadness** [comment]
I can work on this at the weekend.

@hbj Are you ok with the solution from the [comment](https://github.com/allmas-tn/sequelize-transforms/issues/4#issuecomment-332191017) above?

**Comment by hbj** [comment]
@sameoldmadness there is already a PR for this #5, just waiting for the contributor to make some changes. If it takes too long I'll just merge it and make the changes myself.

**Comment by sameoldmadness** [comment]
@hbj Great!

Would you mind closing this issue then?

**Comment by hbj** [comment]
Implemented in v2.0.0 b4046f749e2a8dac5654ba3579bda600cc82352d.
