### ISSUE TITLE
Maintenance question

### ISSUE THREAD

**Issue by Kostanos** [allmas-tn/sequelize-transforms#6]
Hi, this is the feature that I'm looking for.
As I don't see any commits here for a while, my question is:

Is this project still up to date, maintained, ready for production use?
Thank you.

**Comment by Kostanos** [comment]
For example, I see this project: https://github.com/domasx2/sequelize-fixtures
which is fresher, but, it is bigger, I don't need the most of functionality that provided there.

**Comment by hbj** [comment]
Hi @Kostanos , sorry for this late reply. I'm not maintaining the project anymore TBH and I used it in production code, but I don't know whether it's compatible with new versions of Sequelize. Please feel free to submit PRs or take over the maintenance of the project if you are interested. Cheers.
